name: Build and Upload to Qiniu

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -trimpath -ldflags="-s -w" -o mockserver-linux-amd64 cmd/server/main.go
      
      - name: Download and setup qshell
        run: |
          wget https://devtools.qiniu.com/qshell-v2.12.0-linux-amd64.tar.gz
          tar -xzf qshell-v2.12.0-linux-amd64.tar.gz
          chmod +x qshell
          ./qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} qiniu
      
      - name: Upload to Qiniu
        run: |
          TAG_NAME=${{ steps.get_tag.outputs.TAG_NAME }}
          REMOTE_PATH="mockserver/${TAG_NAME}_mockserver-linux-amd64"
          ./qshell rput ${{ secrets.QINIU_BUCKET }} "${REMOTE_PATH}" mockserver-linux-amd64
          echo "Uploaded to: ${REMOTE_PATH}"
