name: Build and Upload to Qiniu

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    name: Build and Upload Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -trimpath -ldflags="-s -w" -o mockserver cmd/server/main.go
      
      - name: Create package
        run: |
          TAG_NAME=${{ steps.get_tag.outputs.TAG_NAME }}
          
          mkdir -p ${TAG_NAME}
          cp mockserver ${TAG_NAME}/
          cp etc/mockserver.yaml ${TAG_NAME}/
          
          tar -czf ${TAG_NAME}.tar.gz ${TAG_NAME}
          echo "Created package: ${TAG_NAME}.tar.gz"
          ls -lh ${TAG_NAME}.tar.gz
      
      - name: Download and setup qshell
        run: |
          wget https://github.com/qiniu/qshell/releases/download/v2.16.1/qshell-v2.16.1-linux-amd64.tar.gz
          tar -xzf qshell-v2.16.1-linux-amd64.tar.gz
          chmod +x qshell
          ./qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} qiniu
      
      - name: Upload to Qiniu
        run: |
          TAG_NAME=${{ steps.get_tag.outputs.TAG_NAME }}
          PACKAGE_NAME="${TAG_NAME}.tar.gz"
          REMOTE_PATH="mockserver/${PACKAGE_NAME}"
          ./qshell rput ${{ secrets.QINIU_BUCKET }} "${REMOTE_PATH}" ${PACKAGE_NAME}
          echo "Uploaded to: ${REMOTE_PATH}"
